app_name = "MyApp"

[[resources]]
name = "health"

[[resources.routes]]
method = "GET"
path = "/health"
description = "Returns the health of the API"

[[resources.routes.headers]]
key = "Accept"
values = ["applicaton/json"]

[[resources.routes.responses]]
status = 200
description = "Success"

[[resources.routes.responses.headers]]
key = "Content-Type"
values = ["applicaton/json"]
